[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "api_cpp"
  name = "C++ API"
  url = "api/cpp/index.html"
  weight = 2

[[main]]
  identifier = "api_py"
  name = "Python API"
  url = "api/python/index.html"
  weight = 3
